### ISSUE TITLE
There is something wrong with is buliding the fnf game, It saids "Error: VlcBitmap.cpp"

### ISSUE THREAD

**Issue by MapidsFanAnimator** [TheLeerName/FNF-extra#2]
### Describe your bug here.

Error: VlcBitmap.cpp
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\fileapifromapp.h(71): error C2061: syntax error: identifier 'LPCREATEFILE2_EXTENDED_PARAMETERS'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(6098): error C2061: syntax error: identifier 'STREAM_INFO_LEVELS'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didn't.

**Comment by TheLeerName** [comment]
oh i has this issue, try reinstall visual studio libs or delete export folder
